Controllers/AdminController.cs
using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Utils;
using FPTBook.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;



namespace FPTBook.Controllers
{
    [Authorize(Roles = Role.ADMIN)]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly ApplicationDbContext _context;
        private readonly IPasswordHasher<ApplicationUser> _passwordHash;

        public AdminController(
          UserManager<ApplicationUser> userManager, ApplicationDbContext context, IPasswordHasher<ApplicationUser> passwordHash)
        {
            _userManager = userManager;
            _context = context;
            _passwordHash = passwordHash;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Customers()
        {
            var usersWithPermission = _userManager.GetUsersInRoleAsync(Role.CUSTOMER).Result;
            return View(usersWithPermission);
        }

        [HttpGet]
        public IActionResult StoreOwners()
        {
            var usersWithPermission = _userManager.GetUsersInRoleAsync(Role.OWNER).Result;
            return View(usersWithPermission);
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        [HttpGet]
        public async Task<IActionResult> ChangeStoreOwnerPassword(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction("StoreOwners");
        }
        [HttpGet]
        public async Task<IActionResult> ChangeCustomerPassword(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction("Customers");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeCustomerPassword(string id, string password)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {

                if (!string.IsNullOrEmpty(password))
                    user.PasswordHash = _passwordHash.HashPassword(user, password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("Customers");
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeStoreOwnerPassword(string id, string password)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {

                if (!string.IsNullOrEmpty(password))
                    user.PasswordHash = _passwordHash.HashPassword(user, password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("StoreOwners");
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);

        }
        public IActionResult GenreApproval()
        {
            IEnumerable<Genre> genres = _context.Genres
                                                .Where(t => t.Status == Enums.GenreApproval.pending)
                                                .ToList();
            return View(genres);
        }

        public IActionResult ApproveGenre(int id)
        {
            var genreInDb = _context.Genres.SingleOrDefault(t => t.Id == id);
            if (genreInDb is null)
            {
                return BadRequest();
            }

            genreInDb.Status = Enums.GenreApproval.approved;

            Notification noti = new Notification
            {
                Message = "Your genre request for " + genreInDb.Description + " has been approved",
                NotiStatus = Enums.NotiCheck.unSeen
            };
            _context.Add(noti);
            
            _context.SaveChanges();
            return RedirectToAction("GenreApproval");
        }

        public IActionResult RejectGenre(int id)
        {
            var genreInDb = _context.Genres.SingleOrDefault(t => t.Id == id);
            if (genreInDb is null)
            {
                return BadRequest();
            }

            genreInDb.Status = Enums.GenreApproval.rejected;

            Notification noti = new Notification
            {
                Message = "Your genre request for " + genreInDb.Description + " has been rejected",
                NotiStatus = Enums.NotiCheck.unSeen
            };
            _context.Add(noti);

            _context.SaveChanges();
            return RedirectToAction("GenreApproval");
        }

       
    }
}

Controllers/CustomerController.cs
using Abp.Collections.Extensions;

using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Utils;
using FPTBook.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

using static System.Reflection.Metadata.BlobBuilder;

namespace FPTBook.Controllers
{
    [Authorize(Roles = Role.CUSTOMER)]
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CustomerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index(string title)
        {
            var bookList = new List<BookDisplayViewModel>();
            if (bookList is null)
            {
                return NotFound();
            }

            IEnumerable<Book> books = _context.Books
                 .Include(t => t.Genre)
                 .ToList();
            foreach (var book in books)
            {
                string imageBase64Data = Convert.ToBase64String(book.ImageData);
                string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);

                var newBook = new BookDisplayViewModel()
                {
                    BookId = book.BookId,
                    Title = book.Title,
                    Author = book.Author,
                    Price = book.Price,
                    Genre = book.Genre,
                    BookStatus = book.BookStatus,
                    ImageUrl = image
                };
                bookList.Add(newBook);
            }

            if (!string.IsNullOrWhiteSpace(title))
            {
                return View(bookList.Where(t => t.Title.ToLower()
                .Contains(title.ToLower()))
                  .AsEnumerable());
            }
            else
            {
                return View(bookList.AsEnumerable());
            }

        }

        public async Task<IActionResult> AddToCart(int id)
        {
            var currentUserId = _userManager.GetUserId(User);
            var bookInStore = _context.Books.SingleOrDefault(t => t.BookId == id);
            var bookInCart = _context.Carts
        .SingleOrDefault(t => t.BookId == id && t.UserId == currentUserId);

            if (bookInCart == null)
            {
                var cartItem = new Cart()
                {
                    BookId = id,
                    Title = bookInStore.Title,
                    Author = bookInStore.Author,
                    Price = bookInStore.Price,
                    UserId = currentUserId,
                    Quantity = 1
                };
                _context.Carts.Add(cartItem);
                await _context.SaveChangesAsync();
            }
            else if (bookInCart != null)
            {
                bookInCart.Quantity++;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult BookDetails(int id)
        {
            var bookInDb = _context.Books
            .Include(t => t.Genre)
            .SingleOrDefault(t => t.BookId == id);
            if (bookInDb is null)
            {
                return NotFound();
            }
            string imageBase64Data = Convert.ToBase64String(bookInDb.ImageData);
            string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);
            ViewBag.ImageData = image;

            return View(bookInDb);
        }
    }


}

Controllers/StoreOwnerController.cs
using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Utils;
using FPTBook.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FPTBook.Controllers
{
  [Authorize(Roles = Role.OWNER)]
  public class StoreOwnerController : Controller
    {
        private ApplicationDbContext _context;
        public StoreOwnerController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string word)
        {
            if (!string.IsNullOrWhiteSpace(word))
            {
                var result = _context.Books
                  .Include(t => t.Genre)
                  .Where(t => t.Title.Contains(word) || t.Genre.Description.Contains(word))
                  .ToList();

                return View(result);
            }

            IEnumerable<Book> books = _context.Books
            .Include(t => t.Genre)
            .ToList();

            return View(books);
        }
        [HttpGet]
        public IActionResult Insert()
        {
          var viewModel = new BookGenreViewModel()
          {
            Genres = _context.Genres.ToList()
          };
          return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Insert(BookGenreViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel = new BookGenreViewModel
                {
                    Genres = _context.Genres.ToList()
                };
                return View(viewModel);
            }
            using (var memoryStream = new MemoryStream())
            {
                await viewModel.FormFile.CopyToAsync(memoryStream);
                var newBook = new Book
                {
                    Title = viewModel.Book.Title,
                    Price = viewModel.Book.Price,
                    Author = viewModel.Book.Author,
                    GenreId = viewModel.Book.GenreId,
                    BookStatus = Enums.BookStatus.inStock,
                    ImageData = memoryStream.ToArray()
                };
                _context.Add(newBook);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var bookInDb = _context.Books.SingleOrDefault(t => t.BookId == id);
            if (bookInDb is null)
            {
                return NotFound();
            }

            var viewModel = new BookGenreViewModel()
            {
                Book = bookInDb,
                Genres = _context.Genres.ToList()
            };
            return View(viewModel);
        }


    [HttpPost]
    public async Task<IActionResult> Update(BookGenreViewModel viewModel)
    {

      using (var memoryStream = new MemoryStream())
      {
        //If there is file
        if (viewModel.FormFile != null)
        {
          await viewModel.FormFile.CopyToAsync(memoryStream);
          var bookInDb = _context.Books.SingleOrDefault(t => t.BookId == viewModel.Book.BookId);
          if (bookInDb is null)
          {
            return BadRequest();
          }
          if (!ModelState.IsValid)
          {
            viewModel = new BookGenreViewModel()
            {
              Book = viewModel.Book,
              Genres = _context.Genres.ToList()
            };
            return View(viewModel);
          }
          bookInDb.Title = viewModel.Book.Title;
          bookInDb.Author = viewModel.Book.Author;
          bookInDb.BookStatus = viewModel.Book.BookStatus;
          bookInDb.Price = viewModel.Book.Price;
          bookInDb.GenreId = viewModel.Book.GenreId;
          bookInDb.ImageData = memoryStream.ToArray();
          _context.SaveChanges();
        }
        else //If there is no file
        {
          var bookInDb = _context.Books.SingleOrDefault(t => t.BookId == viewModel.Book.BookId);
          if (bookInDb is null)
          {
            return BadRequest();
          }
          if (!ModelState.IsValid)
          {
            viewModel = new BookGenreViewModel()
            {
              Book = viewModel.Book,
              Genres = _context.Genres.ToList()
            };
            return View(viewModel);
          }
          bookInDb.Title = viewModel.Book.Title;
          bookInDb.Author = viewModel.Book.Author;
          bookInDb.BookStatus = viewModel.Book.BookStatus;
          bookInDb.Price = viewModel.Book.Price;
          bookInDb.GenreId = viewModel.Book.GenreId;
          _context.SaveChanges();
        }
      }
      return RedirectToAction("Index");
    }
    [HttpGet]
        public IActionResult Details(int id)
        {
            var bookInDb = _context.Books
            .Include(t => t.Genre)
            .SingleOrDefault(t => t.BookId == id)
              ;
            if (bookInDb is null)
            {
                return NotFound();
            }
           string imageBase64Data = Convert.ToBase64String(bookInDb.ImageData);
           string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);
           ViewBag.ImageData = image;


           return View(bookInDb);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var bookInDb = _context.Books.SingleOrDefault(t => t.BookId == id);
            if (bookInDb is null)
            {
                return NotFound();
            }
     
            _context.Books.Remove(bookInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult GenreList()
        {
            var genres = _context.Genres.Include(t => t.Books).ToList();

            return View(genres);
        }

        [HttpGet]
        public IActionResult GenreRequest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GenreRequest(int id, string description)
        { 
          if(description != null)
          {
            Genre genre = new Genre()
             {
              Id = id,
              Description = description,
              Status = Enums.GenreApproval.pending
             };
        _context.Add(genre);
          }
          else
          {
            return RedirectToAction("GenreRequest");
          }
            await _context.SaveChangesAsync();
            return RedirectToAction("GenreList");
        }
        public IActionResult ReadMessage(int id)
        {
            var notiInDb = _context.Notifications.SingleOrDefault(t => t.NotiId == id);
            if (notiInDb is null)
            {
                return BadRequest();
            }

            notiInDb.NotiStatus = Enums.NotiCheck.seen;

            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> OrderList()
        {
            var orderList = _context.Orders.Include(t=> t.CartList).ToList();

            await _context.SaveChangesAsync();
            return View(orderList.AsEnumerable());
        }
    }
}

 

Views/Home/FAQs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    div.col-sm-9 div {
        height: 250px;
        font-size: 28px;
    }
</style>

<body data-spy="scroll" data-target="#myScrollspy" data-offset="20">

    <div class="container">
        <div class="row">
            <div class="col-sm-4" id="myScrollspy">
                <ul class="nav-pills" style="list-style-type: none;">
                    <li class="active border rounded p-2"><a href="#section1" class="text-decoration-none">Do you offer a guarantee? Can I return my items?</a></li>
                    <li class="border rounded p-2"><a href="#section2" class="text-decoration-none">Do you ship to my country?</a></li>
                    <li class="border rounded p-2"><a href="#section3" class="text-decoration-none">How long does shipping take? When will I receive my order?</a></li>
                    <li class="border rounded p-2"><a href="#section4" class="text-decoration-none">Do you have a phone number I can contact?</a></li>
                    <li class="border rounded p-2"><a href="#section5" class="text-decoration-none">I received a package, but it wasn't my order</a></li>
                </ul>
            </div>
            <div class="col-sm-8">
                <div id="section1">
                    <h4>Do you offer a guarantee? Can I return my items?</h4>
                    <p>
                        Of course. We offer an extended 30 day guarantee!
                        If you aren’t 100% satisfied with your items, or received faulty goods, simply email our customer support team at  info@notebooktherapy.com. Please include the email address associated with the order and describe the issue, include photos if possible. We always aim to respond in 3 days or less!
                    </p>
                </div>
                <hr class="m-0 pt-2 mt-2">
                <div id="section2">
                    <h4>Do you ship to my country?</h4>
                    <p>
                        Yes. We proudly ship worldwide!
                        We’ve shipped cute stationery free to over 200+ countries and we love adding more to the list!
                        Plus you get free worldwide tracked shipping on all orders over $40
                        See the next question for detailed shipping times.
                    </p>
                </div>
                <hr class="m-0 pt-2 mt-2">
                <div id="section3">
                    <h4>How long does shipping take? When will I receive my order?</h4>
                    <p>
                        It all depends on where you are in the world!
                        Find your region and estimated delivery time.
                        Tracking numbers are sent by email after a short processing period.
                        It usually takes us 1-5 days to process orders. We aim to ship all items on-time, but in rare cases it can take longer. Any orders not received within 8 weeks qualify for a full-refund or reship.
                    </p>
                </div>
                <hr class="m-0 pt-2 mt-2">
                <div id="section4">
                    <h4>Do you have a phone number I can contact?</h4>
                    <p>
                        We currently don’t have a phone number for customer service inquiries, but we recommend taking a look around our Help Center to find answers to your questions/concerns.
                        If you can’t find what you’re looking for or need help regarding your order, our Customer Care team will be more than happy to assist you!
                    </p>
                </div>
                <hr class="m-0 pt-2 mt-2">
                <div id="section5">
                    <h4>I received a package, but it wasn't my order</h4>
                    <p>
                        We’re so sorry for the mix up with your order! Please email our Customer Care team by clicking  HERE with your order number and pictures of the following: the stamped initial/number on the outside of your envelope or box, the order packing slip with with the stamped initial visible, and a picture of the products you did receive. Please note that all order issues must be reported within 14 days of delivery.
                    </p>
                </div>
                <hr class="m-0 pt-2 mt-2">
            </div>
        </div>
    </div>

</body>

Views/Home/Index.cshtml
@using FPTBook.Utils
@{
    ViewData["Title"] = "Home Page";
}

@using FPTBook.ViewModels
@model BookNotificationViewModel

<style>
    .container {
        position: relative;
    }

    .hero-image {
        filter: blur(2px);
        width: 100%;
    }

    .hero-text {
        text-align: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: white;
    }

    .flex-container {
        display: flex;
        flex-wrap: wrap;
    }

    .flex-item {
        margin: 20px;
    }

    img {
        width: 318px;
        height: 490px;
    }

    .book-container {
        position: relative;
        width: 318px;
    }

    .overlay {
        background-color: black;
        opacity: 0.8;
        position: absolute;
        bottom: 100%;
        left: 0;
        right: 0;
        overflow: hidden;
        width: 100%;
        height: 0;
        transition: .3s ease;
    }

    .book-container:hover .overlay {
        bottom: 0;
        height: 100%;
    }

    .overlay-price {
        white-space: nowrap;
        color: white;
        font-size: 20px;
        font-weight: bolder;
        text-align: center;
    }

    .overlay-item {
        opacity: 1;
        position: absolute;
        overflow: hidden;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .dropdown-menu {
        white-space: nowrap;
    }

</style>

@if (!User.Identity.IsAuthenticated)
{
    <div class="jumbotron jumbotron-fluid">
        <div class="row">
            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4">Are you new here ?</h1>
                    <p class="lead">Be one of our users</p>
                </div>
                <hr class="my-4">
                <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-primary btn-lg" role="button">Register now</a>
            </div>

            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4">Been here before ?</h1>
                    <p class="lead">Sign in to your account</p>
                </div>
                <hr class="my-4">
                <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-primary btn-lg" role="button">Login now</a>
            </div>
        </div>
    </div>

    <div class="flex-container">
        @foreach (var item in Model.BookDisplay)
        {
            <div class="flex-item book-container">
                <div class="card shadow">
                    <p class="lead">@item.Title</p>
                    <p class="blockquote-footer">@item.Author</p>

                    <img class="card-img-top" src="@item.ImageUrl" />
                    <div class="overlay">
                        <div class="overlay-item">
                            <span class="overlay-price">$ @item.Price</span>

                            @if (@item.BookStatus == FPTBook.Enums.BookStatus.inStock)
                            {
                                <span class="badge badge-success">In Stock</span>
                            }
                            else
                            {
                                <span class="badge badge-danger">Out Of Stock</span>
                            }


                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
}
else if (User.IsInRole(Role.ADMIN))
{
    <h2 class="display-2 text-center">Welcome Admin</h2>
    <div class="jumbotron jumbotron-fluid">
        <div class="row">
            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4" style="text-align: center;">User Accounts Management</h1>
                    <p class="lead">See all customer and store owner account - Reset passwords</p>
                </div>
                <hr class="my-4">
                <a asp-controller="Admin" asp-action="Index" class="btn btn-primary btn-lg" role="button">Manage</a>
            </div>

            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4" style="text-align: center;">Genre Request Approval</h1>
                    <p class="lead">Approve or Reject genre request sent by Store Owner</p>
                </div>
                <hr class="my-4">
                <a asp-controller="Admin" asp-action="GenreApproval" class="btn btn-primary btn-lg" role="button">See Request</a>
            </div>
        </div>
    </div>
}
else if (User.IsInRole(Role.OWNER)){
    <h2 class="display-2 text-center">Welcome Store Owner</h2>

    <div class="d-flex justify-content-center">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Notifications
            </button>
            <div class="dropdown-menu">
                @foreach (var message in Model.Notifications)
                {
                    <ul class="px-2 list-inline">
                        <li class="list-inline-item mx-1 my-0">@message.Message</li>
                        <li class="list-inline-item mx-1 my-0">
                            <a asp-controller="StoreOwner" asp-action="ReadMessage" asp-route-id="@message.NotiId" class="btn close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </a>
                        </li>
                        
                    </ul>
                    <hr class="m-0 pt-2 mt-2" />
                }
            </div>
        </div>
    </div>

    <div class="jumbotron jumbotron-fluid">
        <div class="row">
            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4" style="text-align: center;">Books Management</h1>
                    <p class="lead">Insert, Update, See details or Delete books</p>
                </div>
                <hr class="my-4">
                <a asp-controller="StoreOwner" asp-action="Index" class="btn btn-primary btn-lg" role="button">Manage</a>
            </div>

            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4" style="text-align: center;">Genre Request</h1>
                    <p class="lead">See all genres and send genre request to Admin</p>
                </div>
                <hr class="my-4">
                <a asp-controller="StoreOwner" asp-action="GenreList" class="btn btn-primary btn-lg" role="button">Manage</a>
            </div>

            <div class="d-flex flex-column col">
                <div class="container">
                    <h1 class="display-4" style="text-align: center;">Orders Management</h1>
                    <p class="lead">See all past orders made by customers</p>
                </div>
                <hr class="my-4">
                <a asp-controller="StoreOwner" asp-action="OrderList" class="btn btn-primary btn-lg" role="button">View</a>
            </div>
        </div>
    </div>
} else if (User.IsInRole(Role.CUSTOMER)){
    <div class="container">
        <img class="hero-image" src="https://images.pexels.com/photos/214659/pexels-photo-214659.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" />
        <div class="hero-text">
            <h1 class="display-2">FPTBook</h1>
            <p class="display-4">All you can find</p>
            <a asp-controller="Customer" asp-action="Index" class="btn btn-primary">Shop now</a>
        </div>
    </div>
}