Models/Cart.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FPTBook.Models
{
    public class Cart
    {
        
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        public int BookId { get; set; }
        public Book Book { get; set; }
        public string Title { get; set; }
        public float Price { get; set; }
        public string Author { get; set; }
        public int Quantity { get; set; }
        [Required]
        public ApplicationUser User { get; set; }
    }
}

Controllers/CartController.cs
using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Utils;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.EntityFrameworkCore;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FPTBook.Controllers
{
    [Authorize(Roles = Role.CUSTOMER)]
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var currentUserId = _userManager.GetUserId(User);
            var orderInDb = _context.Orders;

            IEnumerable<Cart> booksInCart = _context.Carts
                  .Include(t => t.Book)
                  .Where(t => t.UserId == currentUserId)
                  .ToList();
            if (!booksInCart.Any())
            {
                return View("EmptyCart");
            }
            else
            {
                return View(booksInCart);
            }

        }

        public IActionResult EmptyCart()
        {
            return View();
        }

        public IActionResult QuantityUp(int id)
        {
            var bookInCart = _context.Carts.SingleOrDefault(t => t.Id == id);
            if (bookInCart == null)
            {
                return NotFound();
            }
            bookInCart.Quantity += 1;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult QuantityDown(int id)
        {
            var bookInCart = _context.Carts.SingleOrDefault(t => t.Id == id);
            if (bookInCart == null)
            {
                return NotFound();
            }
            if (bookInCart.Quantity > 1)
            {
                bookInCart.Quantity -= 1;
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var cartBook = _context.Carts;
            var bookInCart = _context.Carts.SingleOrDefault(t => t.Id == id);
            if (bookInCart == null)
            {
                return NotFound();
            }
            cartBook.Remove(bookInCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> CheckOut()
        {


            var currentUserId = _userManager.GetUserId(User);
            var orderInDb = _context.Orders;

            var ordersNotPaid = _context.Orders
            .Include(t => t.CartList)
            .Where(t => t.UserId == currentUserId && t.OrderStatus == Enums.OrderStatus.notPaid)
            .ToList();

            var cartBooks = _context.Carts
              .Include(t => t.Book)
              .Where(t => t.UserId == currentUserId)
              .ToList();

            float total = 0;


            //Remove all the unpaid
            foreach (var order in ordersNotPaid)
            {
                orderInDb.Remove(order);
                await _context.SaveChangesAsync();
            }
            //Get total
            foreach (var book in cartBooks)
            {
                total += (book.Price * book.Quantity);
            }
            //Add New Order
            var newOrder = new Order()
            {
                CartList = cartBooks,
                Total = total,
                OrderStatus = Enums.OrderStatus.notPaid,
                UserId = currentUserId
            };
            orderInDb.Add(newOrder);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Order");

        }

    }
}

Controllers/CustomerController.cs
using Abp.Collections.Extensions;

using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Utils;
using FPTBook.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

using static System.Reflection.Metadata.BlobBuilder;

namespace FPTBook.Controllers
{
    [Authorize(Roles = Role.CUSTOMER)]
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CustomerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index(string title)
        {
            var bookList = new List<BookDisplayViewModel>();
            if (bookList is null)
            {
                return NotFound();
            }

            IEnumerable<Book> books = _context.Books
                 .Include(t => t.Genre)
                 .ToList();
            foreach (var book in books)
            {
                string imageBase64Data = Convert.ToBase64String(book.ImageData);
                string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);

                var newBook = new BookDisplayViewModel()
                {
                    BookId = book.BookId,
                    Title = book.Title,
                    Author = book.Author,
                    Price = book.Price,
                    Genre = book.Genre,
                    BookStatus = book.BookStatus,
                    ImageUrl = image
                };
                bookList.Add(newBook);
            }

            if (!string.IsNullOrWhiteSpace(title))
            {
                return View(bookList.Where(t => t.Title.ToLower()
                .Contains(title.ToLower()))
                  .AsEnumerable());
            }
            else
            {
                return View(bookList.AsEnumerable());
            }

        }

        public async Task<IActionResult> AddToCart(int id)
        {
            var currentUserId = _userManager.GetUserId(User);
            var bookInStore = _context.Books.SingleOrDefault(t => t.BookId == id);
            var bookInCart = _context.Carts
        .SingleOrDefault(t => t.BookId == id && t.UserId == currentUserId);

            if (bookInCart == null)
            {
                var cartItem = new Cart()
                {
                    BookId = id,
                    Title = bookInStore.Title,
                    Author = bookInStore.Author,
                    Price = bookInStore.Price,
                    UserId = currentUserId,
                    Quantity = 1
                };
                _context.Carts.Add(cartItem);
                await _context.SaveChangesAsync();
            }
            else if (bookInCart != null)
            {
                bookInCart.Quantity++;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult BookDetails(int id)
        {
            var bookInDb = _context.Books
            .Include(t => t.Genre)
            .SingleOrDefault(t => t.BookId == id);
            if (bookInDb is null)
            {
                return NotFound();
            }
            string imageBase64Data = Convert.ToBase64String(bookInDb.ImageData);
            string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);
            ViewBag.ImageData = image;

            return View(bookInDb);
        }
    }


}

Views/Cart/EmptyCart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="form-group">
    <a asp-controller="Customer" asp-action="Index" class="btn btn-outline-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
            <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
        </svg>  Back to Store
    </a>
</div>

<div class="container-fluid">
    <div class="row px-5">
        <div class="col-md-7">
            <div class="shopping-cart">
                <h6 style="font-weight: bold;">My Shopping Cart</h6>
                <hr>
                <p class="lead">There is nothing here</p>
            </div>
        </div>
        <div class="col-md-4 offset-md-1 border rounded mt-5 bg-white h-25">
            <div class="pt-4">
                <h6 style="font-weight: bold;">PRICE DETAILS</h6>
                <hr>
                <div class="row price-details">
                    <div class="col-md-6">
                        <div class="col-md-6">
                            Total
                        </div>
                    </div>
                    <a asp-controller="Cart" asp-action="CheckOut" class="btn btn-warning disabled" aria-disabled="true">CHECK OUT</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Cart/Index.cshtml
@model IEnumerable<Cart>

<div class="form-group">
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
            <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
        </svg>  Back to Home
    </a>
</div>

@{
    float Total = 0;
}

<div class="container-fluid">
    <div class="row px-5">
        <div class="col-md-7">
            <div class="shopping-cart">
                <h6 style="font-weight: bold;">My Shopping Cart</h6>
                <hr>
                @foreach (var item in Model)
                {
                    <form class="cart-items">
                        <div class="border rounded">
                            <div class="row bg-white">
                                @*<div class="col-md-3 pl-0">
                                    <img class="img-fluid" src="@item.ViewBag.ImageUrl">
                                </div>*@
                                <div class="col-md-6">
                                    <h5 class="pt-2" style="font-weight: bold; font-size: 26px;">@item.Book.Title</h5>
                                    <h5 class="pt-2 blockquote-footer">@item.Book.Author</h5>
                                    <h5 class="pt-2">$ @item.Book.Price</h5>

                                    <a asp-controller="Cart" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2">Remove</a>
                                </div>
                                <div class="col-md-3 py-5">
                                    <div>
                                        <p>Quantity: @item.Quantity</p>
                                    </div>
                                    @{
                                        var SubTotal = @item.Quantity * @item.Book.Price;
                                        Total += SubTotal;
                                        <h5 class="pt-2">$ @SubTotal</h5>
                                    }
                                    <a asp-controller="Cart" asp-action="QuantityDown" asp-route-id=@item.Id class="btn btn-light" style="border-radius: 50px;">-</a>
                                    <a asp-controller="Cart" asp-action="QuantityUp" asp-route-id=@item.Id class="btn btn-light" style="border-radius: 50px;">+</a>
                                </div>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
        <div class="col-md-4 offset-md-1 border rounded mt-5 bg-white h-25">
            <div class="pt-4">
                <h6 style="font-weight: bold;">PRICE DETAILS</h6>
                <hr>
                <div class="row">
                    <div class="col-sm-7">
                        @{
                            <p class="lead">Total Price: $@Total</p>
                        }
                    </div>
                    <div class="col-sm-5">
                        <a asp-controller="Cart" asp-action="CheckOut" class="btn btn-warning btn-sm">CHECK OUT</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>